# Generated by Django 4.1 on 2022-08-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='settings_file_info',
            field=models.TextField(blank=True, verbose_name='Обычное расположение файла с настройками биндов'),
        ),
    ]
