import type { KeyBindings, ModifierSlot } from '../types/keymap';

const LETTER_KEYS = new Set('abcdefghijklmnopqrstuvwxyz0123456789'.split(''));

const SPECIAL_PUSH: Record<string, string> = {
  tab: '\\t',
  enter: '\\C-m',
  space: ' ',
  escape: '\\e',
  back_space: '\\d',
  up: '\\e[A',
  down: '\\e[B',
  right: '\\e[C',
  left: '\\e[D',
  home: '\\e[H',
  end: '\\e[F',
  insert: '\\e[2~',
  delete: '\\e[3~',
  'page up': '\\e[5~',
  'page down': '\\e[6~',
  f1: '\\eOP',
  f2: '\\eOQ',
  f3: '\\eOR',
  f4: '\\eOS',
  f5: '\\e[15~',
  f6: '\\e[17~',
  f7: '\\e[18~',
  f8: '\\e[19~',
  f9: '\\e[20~',
  f10: '\\e[21~',
  f11: '\\e[23~',
  f12: '\\e[24~',
};

const CSI_LETTER: Record<string, string> = {
  up: 'A',
  down: 'B',
  right: 'C',
  left: 'D',
  home: 'H',
  end: 'F',
  tab: 'Z',
};

const TILDE_CODE: Record<string, string> = {
  insert: '2',
  delete: '3',
  'page up': '5',
  'page down': '6',
  f5: '15',
  f6: '17',
  f7: '18',
  f8: '19',
  f9: '20',
  f10: '21',
  f11: '23',
  f12: '24',
};

const SLOT_TO_CSI_MOD: Partial<Record<ModifierSlot, number>> = {
  s: 2,
  a: 3,
  as: 4,
  c: 5,
  cs: 6,
  ac: 7,
  acs: 8,
};

const SYMBOL_CHARS: Record<string, string> = {
  minus: '-',
  equals: '=',
  open_bracket: '[',
  close_bracket: ']',
  semicolon: ';',
  apostrophe: "'",
  comma: ',',
  period: '.',
  slash: '/',
};

const SHIFTED_CHARS: Record<string, string> = {
  comma: '<',
  period: '>',
  minus: '_',
  '3': '#',
  '8': '*',
  slash: '?',
  back_quote: '~',
  open_bracket: '{',
  close_bracket: '}',
  equals: '+',
  semicolon: ':',
  apostrophe: '"',
};

export function serializeBashInputrc(bindings: KeyBindings): string {
  const lines = [
    '# Generated by keybinds-map — GNU Readline emacs mode',
    'set editing-mode emacs',
    'set keymap emacs',
    '',
  ];

  const rows: Array<{ commandId: string; keyseq: string }> = [];

  for (const [key, slots] of Object.entries(bindings)) {
    if (!key) {
      continue;
    }
    for (const [slot, command] of Object.entries(slots)) {
      if (!command) {
        continue;
      }
      const keyseq = formatKeyseq(slot as ModifierSlot, key);
      if (!keyseq) {
        continue;
      }
      rows.push({ commandId: command.id, keyseq });
    }
  }

  rows.sort((left, right) => left.commandId.localeCompare(right.commandId) || left.keyseq.localeCompare(right.keyseq));

  for (const { commandId, keyseq } of rows) {
    lines.push(`"${keyseq}": ${commandId}`);
  }

  lines.push('');
  return lines.join('\n');
}

export function formatKeyseq(slot: ModifierSlot, key: string): string | null {
  if (slot === 'push') {
    if (SPECIAL_PUSH[key]) {
      return SPECIAL_PUSH[key];
    }
    if (LETTER_KEYS.has(key)) {
      return key;
    }
    if (SYMBOL_CHARS[key]) {
      return SYMBOL_CHARS[key];
    }
    return null;
  }

  if (CSI_LETTER[key] && SLOT_TO_CSI_MOD[slot]) {
    const modifier = SLOT_TO_CSI_MOD[slot];
    if (key === 'tab' && slot === 's') {
      return '\\e[Z';
    }
    return `\\e[1;${modifier}${CSI_LETTER[key]}`;
  }

  if (TILDE_CODE[key] && SLOT_TO_CSI_MOD[slot]) {
    return `\\e[${TILDE_CODE[key]};${SLOT_TO_CSI_MOD[slot]}~`;
  }

  const char = LETTER_KEYS.has(key) ? key : SYMBOL_CHARS[key];
  if (char && slot === 'c') {
    return `\\C-${char}`;
  }
  if (char && slot === 'a') {
    return `\\M-${char}`;
  }
  if (char && slot === 'ac') {
    return `\\M-\\C-${char}`;
  }

  const shifted = SHIFTED_CHARS[key];
  if (shifted) {
    if (slot === 'as') {
      return `\\M-${shifted}`;
    }
    if (slot === 'cs') {
      return `\\C-${shifted}`;
    }
    if (slot === 'acs') {
      return `\\M-\\C-${shifted}`;
    }
  }

  return null;
}

export function downloadInputrc(filename: string, contents: string): void {
  const blob = new Blob([contents], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}
