import type {
  ModifierSlot,
  VimBinding,
  VimMode,
} from '../types/keymap';

const MODE_MAP_CMD: Record<VimMode, string> = {
  normal: 'nnoremap',
  insert: 'inoremap',
  visual: 'vnoremap',
  cmdline: 'cnoremap',
};

const KEY_TO_VIM: Record<string, string> = {
  escape: '<Esc>',
  enter: '<CR>',
  tab: '<Tab>',
  space: '<Space>',
  back_space: '<BS>',
  delete: '<Del>',
  insert: '<Insert>',
  home: '<Home>',
  end: '<End>',
  up: '<Up>',
  down: '<Down>',
  left: '<Left>',
  right: '<Right>',
  'page up': '<PageUp>',
  'page down': '<PageDown>',
  minus: '-',
  equals: '=',
  open_bracket: '[',
  close_bracket: ']',
  back_quote: '`',
  semicolon: ';',
  apostrophe: "'",
  comma: ',',
  period: '.',
  slash: '/',
};

const SLOT_PREFIX: Record<ModifierSlot, string> = {
  push: '',
  a: '<A-',
  c: '<C-',
  s: '',
  ac: '<A-C-',
  as: '<A-S-',
  cs: '<C-S-',
  acs: '<A-C-S-',
};

function keyToken(keyName: string, slot: ModifierSlot): string | null {
  const base = KEY_TO_VIM[keyName] ?? (keyName.length === 1 ? keyName : null);
  if (!base) {
    return null;
  }

  if (slot === 'push') {
    return base.startsWith('<') ? base : base;
  }

  if (slot === 's') {
    if (base.length === 1 && /[a-z]/.test(base)) {
      return base.toUpperCase();
    }
    // Shift of symbol keys — emit as Vim notation when known
    const shiftSym: Record<string, string> = {
      '4': '$',
      '3': '#',
      '5': '%',
      '6': '^',
      '8': '*',
      semicolon: ':',
      slash: '?',
      comma: '<',
      period: '>',
      back_quote: '~',
      apostrophe: '"',
      '1': '!',
      '2': '@',
      '7': '&',
      '9': '(',
      '0': ')',
      minus: '_',
      equals: '+',
      open_bracket: '{',
      close_bracket: '}',
    };
    return shiftSym[keyName] ?? null;
  }

  const prefix = SLOT_PREFIX[slot];
  if (!prefix) {
    return null;
  }
  const inner = base.startsWith('<') ? base.slice(1, -1) : base;
  if (prefix.endsWith('-')) {
    return `${prefix}${inner}>`;
  }
  return null;
}

export function serializeVimKeymap(
  vimBindings: VimBinding[],
  options?: { includeLayerComments?: boolean },
): string {
  const lines: string[] = [
    '" Generated by keybinds-map — Vim curated map',
    '" Prefix layers and textobjects: see comments; operator+motion not expanded.',
    '',
  ];

  const byMode: Record<VimMode, VimBinding[]> = {
    normal: [],
    insert: [],
    visual: [],
    cmdline: [],
  };

  for (const binding of vimBindings) {
    byMode[binding.mode].push(binding);
  }

  for (const mode of Object.keys(byMode) as VimMode[]) {
    const entries = byMode[mode];
    if (!entries.length) {
      continue;
    }
    lines.push(`" --- ${mode} ---`);
    const cmd = MODE_MAP_CMD[mode];
    for (const binding of entries) {
      if (binding.layer) {
        if (options?.includeLayerComments !== false) {
          const token = keyToken(binding.keyName, binding.slot);
          lines.push(
            `" layer ${binding.layer}: ${token ?? binding.keyName} → ${binding.commandId}`,
          );
        }
        continue;
      }
      const lhs = keyToken(binding.keyName, binding.slot);
      if (!lhs) {
        lines.push(`" skip unknown key ${binding.keyName}/${binding.slot} → ${binding.commandId}`);
        continue;
      }
      // RHS is a placeholder label — curated map IDs are not Vimscript functions.
      lines.push(`${cmd} ${lhs} <Nop> | " ${binding.commandId}`);
    }
    lines.push('');
  }

  lines.push('" Textobjects / operators: use native Vim grammar (d/c/y + motion/iw/aw).');
  return `${lines.join('\n')}\n`;
}

export function downloadVimrc(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename.endsWith('.vim') ? filename : `${filename}.vim`;
  anchor.click();
  URL.revokeObjectURL(url);
}

/** Minimal import of nmap/nnoremap/imap/inoremap/vmap/vnoremap lines. */
export function parseVimrcMaps(source: string): {
  bindings: VimBinding[];
  warnings: string[];
} {
  const warnings: string[] = [];
  const bindings: VimBinding[] = [];
  const mapRe =
    /^\s*(?:([nvxi])?(?:nore)?map|([nvxi])noremap)\s+(\S+)\s+(\S+)/i;

  const modeFrom = (flags: string | undefined): VimMode | null => {
    const f = (flags ?? 'n').toLowerCase();
    if (f === 'n' || f === '') {
      return 'normal';
    }
    if (f === 'i') {
      return 'insert';
    }
    if (f === 'v' || f === 'x') {
      return 'visual';
    }
    if (f === 'c') {
      return 'cmdline';
    }
    return null;
  };

  for (const line of source.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('"')) {
      continue;
    }
    if (/<Plug>/i.test(trimmed) || /<leader>/i.test(trimmed)) {
      warnings.push(`Пропущено (Plug/leader): ${trimmed}`);
      continue;
    }
    const match = trimmed.match(mapRe);
    if (!match) {
      if (/\bmap\b/i.test(trimmed)) {
        warnings.push(`Не разобрано: ${trimmed}`);
      }
      continue;
    }
    const mode = modeFrom(match[1] ?? match[2]);
    if (!mode) {
      warnings.push(`Неизвестный режим map: ${trimmed}`);
      continue;
    }
    const lhs = match[3];
    const decoded = decodeVimLhs(lhs);
    if (!decoded) {
      warnings.push(`Неизвестный lhs: ${lhs}`);
      continue;
    }
    if (decoded.chord) {
      warnings.push(`Пропущен chord/prefix map: ${lhs}`);
      continue;
    }
    bindings.push({
      commandId: `user:${match[4]}`,
      mode,
      keyName: decoded.keyName,
      slot: decoded.slot,
      layer: null,
    });
  }

  return { bindings, warnings };
}

function decodeVimLhs(
  lhs: string,
): { keyName: string; slot: ModifierSlot; chord?: boolean } | null {
  if (/^<C-W>/i.test(lhs) && lhs.length > 4) {
    return { keyName: 'w', slot: 'c', chord: true };
  }
  const ctrl = /^<C-([A-Za-z0-9])>$/i.exec(lhs);
  if (ctrl) {
    return { keyName: ctrl[1].toLowerCase(), slot: 'c' };
  }
  const alt = /^<A-([A-Za-z0-9])>$/i.exec(lhs);
  if (alt) {
    return { keyName: alt[1].toLowerCase(), slot: 'a' };
  }
  const named: Record<string, string> = {
    '<Esc>': 'escape',
    '<CR>': 'enter',
    '<Tab>': 'tab',
    '<Space>': 'space',
    '<BS>': 'back_space',
    '<Del>': 'delete',
  };
  if (named[lhs]) {
    return { keyName: named[lhs], slot: 'push' };
  }
  if (lhs.length === 1) {
    if (/[A-Z]/.test(lhs)) {
      return { keyName: lhs.toLowerCase(), slot: 's' };
    }
    const sym: Record<string, { keyName: string; slot: ModifierSlot }> = {
      $: { keyName: '4', slot: 's' },
      '#': { keyName: '3', slot: 's' },
      '%': { keyName: '5', slot: 's' },
      '^': { keyName: '6', slot: 's' },
      '*': { keyName: '8', slot: 's' },
      ':': { keyName: 'semicolon', slot: 's' },
      '?': { keyName: 'slash', slot: 's' },
      ';': { keyName: 'semicolon', slot: 'push' },
      '/': { keyName: 'slash', slot: 'push' },
      '.': { keyName: 'period', slot: 'push' },
      ',': { keyName: 'comma', slot: 'push' },
      "'": { keyName: 'apostrophe', slot: 'push' },
      '`': { keyName: 'back_quote', slot: 'push' },
      '~': { keyName: 'back_quote', slot: 's' },
    };
    if (sym[lhs]) {
      return sym[lhs];
    }
    if (/[a-z0-9]/.test(lhs)) {
      return { keyName: lhs, slot: 'push' };
    }
  }
  if (lhs.length > 1 && !lhs.startsWith('<')) {
    return { keyName: lhs[0], slot: 'push', chord: true };
  }
  return null;
}
